/**
 * HARD MERGE GATE: the TypeScript engine must reproduce the Python reference engine
 * (data/app/fixtures/scenario_expected.json, generated by scripts/export_scenario_fixtures.py)
 * for every scenario case: funnel counts, every screen-eligible site's Pareto layer, and every
 * example dominator.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseData } from "@/lib/data/schema";
import { computeScenario, type CandidateSetId, type SlopeThreshold } from "@/lib/scenario/scenario";

const DATA = join(__dirname, "..", "..", "data", "app");
const { candidates, meta } = parseData(
  JSON.parse(readFileSync(join(DATA, "candidates.geojson"), "utf8")),
  JSON.parse(readFileSync(join(DATA, "meta.json"), "utf8")),
);
const props = candidates.features.map((f) => f.properties);

interface Case {
  scenario: CandidateSetId; target_mw_ac: number; slope_threshold_pct: number; exclude_nwi: boolean;
  funnel: { universe: number; baseline: number; size_feasible: number; screen_eligible: number; frontier: number };
  ranks: Record<string, number>; example_dominator: Record<string, string>;
}
const cases: Case[] = JSON.parse(readFileSync(join(DATA, "fixtures", "scenario_expected.json"), "utf8")).cases;

describe("golden parity with Python reference engine", () => {
  it("fixture has all 72 cases", () => expect(cases.length).toBe(72));

  for (const c of cases) {
    const name = `${c.scenario} ${c.target_mw_ac} MW slope<=${c.slope_threshold_pct}% nwi=${c.exclude_nwi ? "excluded" : "included"}`;
    it(name, () => {
      const r = computeScenario(props, meta, {
        candidateSet: c.scenario, targetMwAc: c.target_mw_ac,
        slopeThresholdPct: c.slope_threshold_pct as SlopeThreshold, excludeNwi: c.exclude_nwi,
        maxGridKm: null, maxNwiPct: null,
      });
      expect({
        universe: r.funnel.universe, baseline: r.funnel.baseline, size_feasible: r.funnel.sizeFeasible,
        screen_eligible: r.funnel.screenEligible, frontier: r.funnel.frontier,
      }).toEqual(c.funnel);
      const ranks: Record<string, number> = {};
      const doms: Record<string, string> = {};
      for (const id of r.eligibleIds) {
        const s = r.results.get(id)!;
        ranks[id] = s.layer!;
        if (s.exampleDominator) doms[id] = s.exampleDominator;
      }
      expect(ranks).toEqual(c.ranks);
      expect(doms).toEqual(c.example_dominator);
    });
  }
});
