"""Foundation audit analysis on the reconciled v2 dataset (validation, not a production dependency).

Writes docs/analysis/foundation_report.md (+ figures) with every number quoted in
docs/FOUNDATION_AUDIT.md / DATA_FEASIBILITY.md. Re-run after compute_metrics.py.
"""
import json

import geopandas as gpd
import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from _common import ROOT, PROCESSED, METRIC_CRS  # noqa: E402
from ingest_authoritative import INTERIM  # noqa: E402
from compute_metrics import grid_layers  # noqa: E402
from src.analysis.assumptions import ASSUMPTIONS as A, required_usable_acres  # noqa: E402
from src.analysis.pareto import dominance_matrix, pareto_analysis  # noqa: E402
from src.analysis.scenario import Scenario, run_scenario  # noqa: E402
from src.analysis.status import LANDFILL_SCENARIO_STATUSES  # noqa: E402

OUT = ROOT / "docs" / "analysis"
KM_PER_MI = 1.609344
TARGETS = A["target_sizes_mw_ac"]
REP = []


def md(df, f="{:.2f}"):
    cols = list(df.columns)
    s = ["| " + " | ".join(map(str, cols)) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        s.append("| " + " | ".join(f.format(v) if isinstance(v, (float, np.floating)) and pd.notna(v) else str(v)
                                   for v in r.values) + " |")
    return "\n".join(s)


def h(t):
    REP.append(f"\n## {t}\n")


def main():
    d = gpd.read_parquet(PROCESSED / "feasibility_sites.parquet")
    deq_all = gpd.read_parquet(INTERIM / "deq_brownfields.parquet")
    deq = d[d.primary_source == "nc_deq_brownfields"]
    REP.append("# Foundation analysis (auto-generated by scripts/analyze_foundation.py)\n")

    # 1 universe ------------------------------------------------------------------------
    h("1. Candidate universe")
    REP.append(f"- NC DEQ Brownfields polygons in source: {len(deq_all)} (invalid in source: "
               f"{int((~deq_all.deq_geometry_valid_in_source).sum())}, repaired with make_valid; multipart: "
               f"{int((deq_all.deq_part_count > 1).sum())})")
    REP.append(f"- DEQ polygons >= {A['min_gross_acres_pool']:.0f} gross acres (analysed pool): {len(deq)}")
    REP.append("- Pool by site type / status:\n\n" + md(pd.crosstab(d.site_type, d.candidate_status, margins=True)
                                                       .reset_index(), "{:.0f}"))
    REP.append("\n- DEQ Status values in pool (verbatim): " + json.dumps(deq.deq_status.value_counts().to_dict()))
    REP.append("- Screening confidence by source:\n\n" + md(pd.crosstab(d.primary_source, d.screening_confidence)
                                                           .reset_index(), "{:.0f}"))

    # 2 matching + acreage ----------------------------------------------------------------
    h("2. DEQ <-> EPA RE-Powering matching (all 1,363 DEQ projects)")
    c_all = gpd.read_parquet(PROCESSED / "deq_epa_match.parquet")
    REP.append(md(c_all.epa_match_method.value_counts().rename_axis("method").reset_index(), "{:.0f}"))
    m = c_all[c_all.epa_match_method == "id"].copy()
    m["deq_polygon_acres"] = m.to_crs(METRIC_CRS).area / 4046.8564224
    m["diff_acres"] = m.deq_polygon_acres - m.epa_screening_acres
    m["pct_diff"] = 100 * m.diff_acres / m.epa_screening_acres
    m["deq_reported_vs_epa_pct"] = 100 * (m.deq_reported_acres - m.epa_screening_acres) / m.epa_screening_acres
    h("3. Acreage: current DEQ polygon vs EPA screening acreage (ID matches)")
    q = m[["diff_acres", "pct_diff", "deq_reported_vs_epa_pct"]].abs().describe(percentiles=[.5, .9, .95]).T
    REP.append(md(q.reset_index()))
    REP.append(f"\n- within 1%: {(m.pct_diff.abs() <= 1).mean():.1%}; within 10%: {(m.pct_diff.abs() <= 10).mean():.1%}; "
               f">50%: {(m.pct_diff.abs() > 50).sum()} records")
    REP.append(f"- DEQ *reported* BF_Acreage equals EPA acreage (|diff| <= 0.01 ac) for "
               f"{((m.deq_reported_acres - m.epa_screening_acres).abs() <= 0.01).mean():.1%} of matches "
               "-> EPA's NC brownfield acreage is the DEQ-reported acreage at the EPA vintage")
    out = m.reindex(m.pct_diff.abs().sort_values(ascending=False).index).head(8)
    REP.append("\nLargest discrepancies:\n\n" + md(out[["source_id", "name", "deq_part_count", "deq_reported_acres",
                                                      "epa_screening_acres", "deq_polygon_acres", "pct_diff"]]))

    # 4 grid validation -------------------------------------------------------------------
    h("4. Grid: SolarSight current distance vs EPA historical transmission distance")
    lines, subs = grid_layers()
    g = d[d.epa_match_method == "id"].copy()
    g["epa_km"] = g.epa_transmission_distance_miles * KM_PER_MI
    # What origin does EPA measure from? EPA publishes NC records as points, but an exact 0 from a geocoded
    # point is rare, while a boundary-to-line distance is 0 whenever a line crosses the site. Compare the share of
    # exact zeros by NC program, and compare EPA against both of our candidate origins.
    epa_nc = pd.read_parquet(INTERIM / "epa_repowering_nc.parquet")
    zs = epa_nc.assign(zero=pd.to_numeric(epa_nc.TransDist, errors="coerce") == 0).groupby("Program").zero.agg(["size", "mean"])
    REP.append("- share of EPA transmission distances that are exactly 0, by NC program:\n\n"
               + md(zs.rename(columns={"size": "records", "mean": "share_exactly_0"}).reset_index()
                    .sort_values("share_exactly_0", ascending=False), "{:.3f}"))
    # alternative origin for comparison only: our line layer measured from EPA's published point
    epa_pts = gpd.GeoSeries(gpd.points_from_xy(g.epa_lon, g.epa_lat), crs="EPSG:4326").to_crs(METRIC_CRS)
    li = lines.sindex.nearest(epa_pts.values, return_all=False)[1]
    g["ss_from_epa_point_km"] = [p.distance(lines.geometry.iloc[j]) / 1000 for p, j in zip(epa_pts, li)]
    diff_edge = g.grid_line_distance_km - g.epa_km
    diff_pt = g.ss_from_epa_point_km - g.epa_km
    z_ss, z_epa = g.grid_line_distance_km == 0, g.epa_km == 0
    REP.append(f"\n- matched candidates compared: {len(g)}")
    REP.append(f"- polygon-boundary (SolarSight production) vs EPA: median abs diff {diff_edge.abs().median():.3f} km, "
               f"median signed {diff_edge.median():.2f} km, Spearman {g.grid_line_distance_km.corr(g.epa_km, 'spearman'):.2f}, "
               f"within 0.1 km: {(diff_edge.abs() <= 0.1).mean():.0%}")
    REP.append(f"- exact zeros: SolarSight {int(z_ss.sum())}, EPA {int(z_epa.sum())}, both {int((z_ss & z_epa).sum())} "
               f"(EPA is 0 for {int((z_ss & z_epa).sum())} of the {int(z_ss.sum())} sites where a mapped line intersects the boundary)")
    REP.append(f"- alternative origin, OSM >=69 kV lines from EPA's published point vs EPA: median abs diff {diff_pt.abs().median():.2f} km, "
               f"Spearman {g.ss_from_epa_point_km.corr(g.epa_km, 'spearman'):.2f}, "
               f"within 0.5 km: {(diff_pt.abs() <= 0.5).mean():.0%}")
    REP.append("- conclusion: EPA's NC Brownfield Projects transmission distances behave as polygon-boundary-to-line distances "
               "(not point-based), measured to EPA's own historical line layer; remaining differences are line definitions "
               "(EPA includes 66 kV and unknown-voltage lines) and data vintage.")
    big = g.assign(diff_pt=diff_pt).reindex(diff_pt.abs().sort_values(ascending=False).index).head(6)
    REP.append("\nLargest disagreements between EPA and the point-origin alternative:\n\n" + md(big[["site_id", "name", "epa_km", "ss_from_epa_point_km",
                                                                      "grid_line_distance_km", "epa_transmission_kv",
                                                                      "nearest_line_kv"]]))
    # brute-force spot checks against all line geometries (independent of sjoin_nearest)
    sample = d.sort_values("site_id").iloc[np.linspace(0, len(d) - 1, 7).astype(int)]
    sc = []
    for r in sample.to_crs(METRIC_CRS).itertuples():
        dist = lines.distance(r.geometry)
        j = dist.idxmin()
        sc.append({"site_id": r.site_id, "pipeline_km": r.grid_line_distance_km, "bruteforce_km": dist.min() / 1000,
                   "nearest_line_kv": lines.kv[j], "geometry_type": lines.geometry[j].geom_type})
    sc = pd.DataFrame(sc)
    sc.to_csv(OUT / "grid_spot_checks.csv", index=False)
    REP.append("\nIndependent brute-force spot checks:\n\n" + md(sc, "{:.4f}"))
    REP.append(f"\nmax |pipeline - bruteforce| = {(sc.pipeline_km - sc.bruteforce_km).abs().max():.6f} km")
    fig, ax = plt.subplots(1, 2, figsize=(11, 4.5))
    ax[0].scatter(g.epa_km, g.ss_from_epa_point_km, s=8, alpha=.6)
    ax[0].plot([0, 10], [0, 10], c="k", lw=.8); ax[0].set_xlim(0, 10); ax[0].set_ylim(0, 10)
    ax[0].set_xlabel("EPA RE-Powering transmission distance (km, historical)")
    ax[0].set_ylabel("OSM >=69 kV line distance from EPA point (km)"); ax[0].set_title("Alternative: from EPA's published point")
    ax[1].scatter(g.epa_km, g.grid_line_distance_km, s=8, alpha=.6, c="#d95f02")
    ax[1].plot([0, 10], [0, 10], c="k", lw=.8); ax[1].set_xlim(0, 10); ax[1].set_ylim(0, 10)
    ax[1].set_xlabel("EPA distance (km)"); ax[1].set_ylabel("SolarSight polygon-boundary distance (km)")
    ax[1].set_title("Production metric (polygon boundary to line)")
    fig.tight_layout(); fig.savefig(OUT / "grid_vs_epa.png", dpi=110)

    # 5 solar resource ----------------------------------------------------------------------
    h("5. Does solar resource variation matter for a fixed project size? (DEQ pool)")
    y = deq.annual_mwh_per_mw_ac.dropna()
    REP.append(f"- annual MWh per MW AC: min {y.min():.0f}, p10 {y.quantile(.1):.0f}, median {y.median():.0f}, "
               f"p90 {y.quantile(.9):.0f}, max {y.max():.0f}; CV {y.std() / y.mean():.2%}")
    REP.append(f"- 10 MW AC project: {10 * y.min():,.0f} - {10 * y.max():,.0f} MWh/yr across all DEQ candidates")
    REP.append(f"- AC capacity factor {deq.ac_capacity_factor.min():.3f}-{deq.ac_capacity_factor.max():.3f}")
    REP.append(f"- Spearman with longitude {deq.annual_mwh_per_mw_ac.corr(deq.longitude, 'spearman'):.2f}, with latitude "
               f"{deq.annual_mwh_per_mw_ac.corr(deq.latitude, 'spearman'):.2f}; model is ~10% above observed NC fleet")
    REP.append(f"- EPA max annual GHI (matched): {deq.epa_max_annual_ghi_kwh_m2_day.min():.2f}-"
               f"{deq.epa_max_annual_ghi_kwh_m2_day.max():.2f} kWh/m2/day")

    # 6 NWI -------------------------------------------------------------------------------
    h("6. NWI integration (DEQ pool)")
    REP.append(f"- nwi_data_status: {json.dumps(d.nwi_data_status.value_counts().to_dict())}; mapping imagery year "
               f"median {d.nwi_mapping_image_year.median():.0f}")
    nw = deq.nwi_wetland_overlap_pct
    REP.append(f"- DEQ candidates with any NWI vegetated-wetland overlap: {(nw > 0).sum()} / {nw.notna().sum()}; "
               f">5%: {(nw > 5).sum()}; >20%: {(nw > 20).sum()}; max {nw.max():.1f}%")
    REP.append(f"- previous 'mapped wetland' layer was OSM natural=wetland (now `osm_mapped_wetland_*`): candidates "
               f"with any OSM-wetland overlap {(d.osm_mapped_wetland_overlap_pct > 0).sum()} vs NWI {(d.nwi_wetland_overlap_pct > 0).sum()}")
    for t in TARGETS:
        req = required_usable_acres(t)
        a_ = (deq.usable_acres_slope10_nwi_not_excluded >= req).sum()
        b_ = (deq.usable_acres_slope10 >= req).sum()
        REP.append(f"- {t:g} MW AC: feasible without NWI exclusion {a_}, with {b_} (changed: {a_ - b_})")

    # 7 terrain formulations -----------------------------------------------------------------
    h("7. Terrain formulations (DEQ baseline statuses, 10 MW AC unless noted)")
    base = deq[deq.candidate_status == "deq_brownfield_record"].copy()
    req10 = required_usable_acres(10)
    models = {
        "A: slope<=10% usable + min whole-site mean slope": ("usable_acres_slope10", "mean_slope_deg"),
        "B: extreme-only (<=25%) + min share of base >10%": ("usable_acres_lt25pct", "steep_gt10pct_share_of_lt25pct_base"),
        "C: extreme-only (<=25%) + min mean slope of base": ("usable_acres_lt25pct", "mean_slope_deg_lt25pct_base"),
        "D: slope<=10% usable + grid only (slope = constraint)": ("usable_acres_slope10", None),
        "D+: slope<=10% usable + min mean slope of usable land": ("usable_acres_slope10", "usable_mean_slope_deg_slope10"),
    }
    rows, fronts = [], {}
    for k, (feas, terr) in models.items():
        s = base[base[feas] >= req10]
        objs = [("grid_line_distance_km", "min")] + ([(terr, "min")] if terr else [])
        r = pareto_analysis(s, objs, id_col="site_id")
        fronts[k] = set(r.frontier.site_id)
        rows.append({"model": k, "feasible": len(s), "frontier": len(r.frontier),
                     "frontier_pct": 100 * len(r.frontier) / max(len(s), 1),
                     "rho(grid, terrain)": s.grid_line_distance_km.corr(s[terr], "spearman") if terr else np.nan,
                     "rho(terrain, whole-site mean slope)": s[terr].corr(s.mean_slope_deg, "spearman") if terr else np.nan,
                     "terrain CV": s[terr].std() / s[terr].mean() if terr else np.nan})
    REP.append(md(pd.DataFrame(rows)))
    REP.append("\nPairwise Jaccard of frontiers:\n\n" + md(pd.DataFrame(
        [[len(fronts[a] & fronts[b]) / max(len(fronts[a] | fronts[b]), 1) for b in fronts] for a in fronts],
        index=[k[:2] for k in fronts], columns=[k[:2] for k in fronts]).reset_index()))
    # slope sensitivity of the frozen formulation
    sens = []
    for t in TARGETS:
        fr = {}
        for s_ in A["slope_exclusion_options_pct"]:
            f_, o, r = run_scenario(d, Scenario(target_mw_ac=t, slope_threshold_pct=s_))
            fr[s_] = set(r.frontier.site_id)
            sens.append({"target_mw_ac": t, "slope_pct": s_, **f_})
        for s_ in (5.0, 15.0):
            sens[-1 if s_ == 15.0 else -3][f"jaccard_vs_10"] = len(fr[s_] & fr[10.0]) / max(len(fr[s_] | fr[10.0]), 1)
    REP.append("\nFrozen formulation (D+) slope-threshold sensitivity:\n\n" + md(pd.DataFrame(sens)))

    # 8 funnels -----------------------------------------------------------------------------
    h("8. Scenario funnels (baseline: DEQ brownfield records, slope 10%, NWI excluded from usable area)")
    rows, keep = [], {}
    for t in TARGETS:
        f_, o, r = run_scenario(d, Scenario(target_mw_ac=t))
        keep[t] = (o, r)
        s = d.set_index("site_id").loc[o[o.screen_eligible].site_id]
        tcol = "usable_mean_slope_deg_slope10"
        rows.append({"target_mw_ac": t, "required_usable_acres": required_usable_acres(t), **f_,
                     "frontier_pct": 100 * f_["pareto_optimal"] / max(f_["screen_eligible"], 1),
                     "rho(grid, terrain)": s.grid_line_distance_km.corr(s[tcol], "spearman"),
                     "grid km p50": s.grid_line_distance_km.median(), "grid zero-distance": int((s.grid_line_distance_km == 0).sum()),
                     "terrain deg p10-p90": f"{s[tcol].quantile(.1):.2f}-{s[tcol].quantile(.9):.2f}"})
    REP.append(md(pd.DataFrame(rows)))
    lay = []
    for t, (o, r) in keep.items():
        rk = o.loc[o.screen_eligible, "pareto_rank"].astype(int)
        lay.append({"target_mw_ac": t, "rank1": int((rk == 1).sum()), "rank2": int((rk == 2).sum()),
                    "rank3": int((rk == 3).sum()), "rank<=3": int((rk <= 3).sum()), "max_rank": int(rk.max())})
    REP.append("\nNon-dominated sorting layers (rank 1 = frontier; rank 2 = frontier once rank-1 sites are removed):\n\n"
               + md(pd.DataFrame(lay), "{:.0f}"))
    # robustness: alternative grid metric and practical-significance tolerances (rejected as defaults)
    alt = []
    for t in TARGETS:
        s_ = d[(d.candidate_status == "deq_brownfield_record") & (d.usable_acres_slope10 >= required_usable_acres(t))]
        row = {"target_mw_ac": t, "n": len(s_), "line_dist_zero": int((s_.grid_line_distance_km <= 0.01).sum()),
               "substation_dist_zero": int((s_.substation_distance_km <= 0.01).sum())}
        for lab_, objs, tol in [("line+slope", [("grid_line_distance_km", "min"), ("usable_mean_slope_deg_slope10", "min")], None),
                                ("substation+slope", [("substation_distance_km", "min"), ("usable_mean_slope_deg_slope10", "min")], None),
                                ("line+substation+slope", [("grid_line_distance_km", "min"), ("substation_distance_km", "min"),
                                                           ("usable_mean_slope_deg_slope10", "min")], None),
                                ("line+slope tol 0.25km/0.5deg", [("grid_line_distance_km", "min"), ("usable_mean_slope_deg_slope10", "min")],
                                 {"grid_line_distance_km": 0.25, "usable_mean_slope_deg_slope10": 0.5})]:
            row[lab_] = len(pareto_analysis(s_, objs, id_col="site_id", tolerances=tol).frontier)
        alt.append(row)
    REP.append("\nFrontier size under alternative formulations (robustness check, not adopted):\n\n" + md(pd.DataFrame(alt), "{:.0f}"))
    other = []
    for name, sc_ in [("landfills (likely_closed + mixed)", Scenario(site_types=["landfill"], statuses=LANDFILL_SCENARIO_STATUSES)),
                      ("quarries, exploratory (likely_closed)", Scenario(site_types=["quarry"], statuses=["likely_closed"])),
                      ("DEQ incl. likely_built_out", Scenario(statuses=["deq_brownfield_record", "likely_built_out"]))]:
        for t in (10.0,):
            f_, _, _ = run_scenario(d, Scenario(**{**sc_.__dict__, "target_mw_ac": t}))
            other.append({"scenario": name, "target_mw_ac": t, **f_})
    REP.append("\nSecondary/exploratory scenarios:\n\n" + md(pd.DataFrame(other)))

    # 9 Pareto sanity ----------------------------------------------------------------------
    h("9. Pareto sanity checks (baseline scenarios)")
    for t, (o, r) in keep.items():
        s = d.set_index("site_id").loc[o[o.screen_eligible].site_id].reset_index()
        objs = r.objectives
        v = s[[ob.name for ob in objs]].to_numpy() * np.array([ob.sign for ob in objs])
        D = dominance_matrix(v)
        brute = set(s.site_id[~D.any(axis=0)])
        dup = s.duplicated([ob.name for ob in objs], keep=False).sum()
        near = 0
        if len(s) > 1:
            z = (v - v.mean(0)) / v.std(0)
            dd = np.sqrt(((z[:, None] - z[None]) ** 2).sum(-1)) + np.eye(len(z)) * 9
            near = int((dd.min(1) < 0.02).sum())
        REP.append(f"- {t:g} MW: frontier == brute force: {brute == set(r.frontier.site_id)}; exact duplicate objective "
                   f"vectors: {dup}; near-duplicates (<0.02 sd): {near}; frontier "
                   f"{json.dumps(r.frontier.site_id.tolist())}")
    o, r = keep[10.0]
    fr = d.set_index("site_id").loc[r.frontier.site_id].sort_values("grid_line_distance_km")
    REP.append("\n10 MW AC frontier:\n\n" + md(fr.reset_index()[[
        "site_id", "name", "city", "deq_status", "usable_area_acres", "estimated_max_capacity_mw_ac",
        "grid_line_distance_km", "usable_mean_slope_deg_slope10", "mean_slope_deg", "nwi_wetland_overlap_pct",
        "building_coverage_pct", "epa_match_method", "epa_transmission_distance_miles"]]))
    s = d.set_index("site_id").loc[o[o.screen_eligible].site_id].reset_index()
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.scatter(s.grid_line_distance_km, s.usable_mean_slope_deg_slope10, s=12, c="#999", label="eligible (10 MW AC)")
    ax.scatter(fr.grid_line_distance_km, fr.usable_mean_slope_deg_slope10, s=40, c="#d95f02", label="Pareto frontier")
    ax.set_xlabel("distance to mapped >=69 kV line (km)"); ax.set_ylabel("mean slope of usable land (deg)")
    ax.legend(); ax.set_title("Baseline 10 MW AC brownfield scenario"); fig.tight_layout()
    fig.savefig(OUT / "frontier_10mw.png", dpi=110)
    REP.append("\nExample explanations (10 MW):\n")
    lab = {"grid_line_distance_km": "distance to mapped >=69 kV line (km)",
           "usable_mean_slope_deg_slope10": "mean slope of usable land (deg)"}
    for sid in r.dominated.sort_values("n_dominators").site_id.head(4):
        REP.append("- " + r.explain(sid, s, labels=lab, fmt={k: "{:.2f}" for k in lab}))

    # does generation change decisions? ---------------------------------------------------
    r3 = pareto_analysis(s, r.objectives + [type(r.objectives[0])("annual_mwh_per_mw_ac", "maximize")], id_col="site_id")
    REP.append(f"\nAdding annual MWh per MW AC as a third objective (10 MW): frontier {len(r.frontier)} -> {len(r3.frontier)} "
               f"(new members owe their place to <= {s.annual_mwh_per_mw_ac.std() / s.annual_mwh_per_mw_ac.mean():.1%} yield CV)")
    (OUT / "foundation_report.md").write_text("\n".join(REP) + "\n")
    print("\n".join(REP))


if __name__ == "__main__":
    main()
